function init(self)
	print("init")
	local path = sys.get_save_file("CaptainCapture", "screencapture.mov")
	local path = "file://localhost/Users/bjornritzl/Downloads/foo.mov"
	capture.start(path)
	msg.post(".", "acquire_input_focus")
end

function on_input(self, action_id, action)
	if action_id == hash("touch") and action.released then
		capture.stop()
	end
end

function on_reload(self)
	-- Add reload-handling code here
	-- Remove this function if not needed
end
