local monarch = require "monarch.monarch"

function init(self)
	msg.post("#", "show_first_screen")
	msg.post(".", "acquire_input_focus")
end

function on_message(self, message_id, message, sender)
	if message_id == hash("show_first_screen") then
		--monarch.show(hash("explorer"))
		monarch.show(hash("recorder"))
	end
end

function on_reload(self)
	-- Add reload-handling code here
	-- Remove this function if not needed
end
